# Generated by Django 4.2 on 2023-06-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='pipol',
        ),
    ]
