# Generated by Django 4.2 on 2023-06-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0004_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
