# Generated by Django 4.2 on 2023-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0005_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
