# Generated by Django 4.2 on 2023-06-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0006_alter_users_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
