# Generated by Django 4.2 on 2023-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0008_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField(max_length=11)),
                ('message', models.CharField(max_length=9999)),
                ('delivery', models.IntegerField(default=0, max_length=99)),
            ],
        ),
    ]
