# Generated by Django 4.2 on 2023-06-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0009_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='username',
            new_name='userID',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
