# Generated by Django 4.2 on 2023-06-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0010_rename_username_msg_userid_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
